// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_game.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_map.cpp"
#include "EWIEGA46WW/moc_player.cpp"
#include "EWIEGA46WW/moc_projectile.cpp"
